apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user-api
  labels:
    app: udagram-user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-user-api
  template:
    metadata:
      labels:
        app: udagram-user-api
    spec:
      containers:
      - name: udagram-user-api
        image: pinmaing/udagram-user-api
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: POSTGRES_DB
        - name: AWS_BUCKET
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: AWS_PROFILE
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: JWT_SECRET
        - name: URL
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: URL
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3